# Generated by Django 5.1 on 2025-12-06 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunktObrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('tytul', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['numer'],
            },
        ),
        migrations.CreateModel(
            name='Sesja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('aktywna', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Glosowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('otwarte', models.BooleanField(default=False)),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('punkt_obrad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glosowanie', to='core.punktobrad')),
            ],
        ),
        migrations.AddField(
            model_name='punktobrad',
            name='sesja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty', to='core.sesja'),
        ),
        migrations.CreateModel(
            name='Wniosek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('punkt_obrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='core.punktobrad')),
                ('radny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Glos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glos', models.CharField(choices=[('za', 'Za'), ('przeciw', 'Przeciw'), ('wstrzymuje', 'Wstrzymuję się')], max_length=10)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('glosowanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.glosowanie')),
            ],
            options={
                'ordering': ['uzytkownik'],
                'unique_together': {('glosowanie', 'uzytkownik')},
            },
        ),
    ]
