# Generated by Django 5.1 on 2026-02-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '000X_kandydat_glosowanie_glos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandydat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
