# Generated by Django 5.1 on 2025-12-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punktobrad',
            name='aktywny',
            field=models.BooleanField(default=False),
        ),
    ]
