# Generated by Django 5.1 on 2026-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_alter_kandydat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesja',
            name='przerwa_czas',
            field=models.IntegerField(blank=True, help_text='Czas przerwy w sekundach', null=True),
        ),
        migrations.AddField(
            model_name='sesja',
            name='przerwa_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
