# Generated by Django 5.1 on 2025-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_punktobrad_aktywny'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesja',
            name='jest_usunieta',
            field=models.BooleanField(default=False),
        ),
    ]
