# Generated by Django 5.1 on 2025-12-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sesja_jest_usunieta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesja',
            options={'ordering': ['data']},
        ),
        migrations.AddField(
            model_name='sesja',
            name='opublikowana',
            field=models.BooleanField(default=False),
        ),
    ]
