# Generated by Django 5.1 on 2026-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sesja_options_sesja_opublikowana'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosowanie',
            name='jawnosc',
            field=models.CharField(choices=[('jawne', 'Jawne'), ('tajne', 'Tajne')], default='jawne', max_length=10),
        ),
        migrations.AddField(
            model_name='glosowanie',
            name='liczba_uprawnionych',
            field=models.PositiveIntegerField(blank=True, help_text='Jeśli puste, system przyjmie liczbę oddanych głosów jako bazę dla większości bezwzględnej.', null=True),
        ),
        migrations.AddField(
            model_name='glosowanie',
            name='wiekszosc',
            field=models.CharField(choices=[('zwykla', 'Większość zwykła'), ('bezwzgledna', 'Większość bezwzględna')], default='zwykla', max_length=15),
        ),
    ]
