# Generated by Django 5.1 on 2026-02-10 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_glosowanie_jawnosc_glosowanie_liczba_uprawnionych_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obecnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obecny', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('radny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obecnosci', to=settings.AUTH_USER_MODEL)),
                ('sesja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obecnosci', to='core.sesja')),
            ],
            options={
                'ordering': ['radny__nazwisko', 'radny__imie'],
                'unique_together': {('sesja', 'radny')},
            },
        ),
    ]
