# Generated by Django 5.1 on 2026-02-10 21:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_obecnosc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Komisja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField(blank=True)),
                ('aktywna', models.BooleanField(default=True)),
                ('czlonkowie', models.ManyToManyField(blank=True, limit_choices_to={'rola': 'radny'}, related_name='komisje', to=settings.AUTH_USER_MODEL)),
                ('przewodniczacy', models.ForeignKey(limit_choices_to={'rola': 'radny'}, on_delete=django.db.models.deletion.PROTECT, related_name='komisje_przewodniczy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nazwa'],
            },
        ),
        migrations.CreateModel(
            name='KomisjaSesja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('aktywna', models.BooleanField(default=True)),
                ('komisja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesje', to='core.komisja')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='KomisjaPunktObrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('tytul', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
                ('aktywny', models.BooleanField(default=False)),
                ('sesja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punkty', to='core.komisjasesja')),
            ],
            options={
                'ordering': ['numer'],
            },
        ),
        migrations.CreateModel(
            name='KomisjaWniosek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('wniosek', 'Wniosek'), ('zapytanie', 'Zapytanie'), ('postulat', 'Postulat')], default='wniosek', max_length=20)),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('wyslany_do_rady', models.BooleanField(default=False)),
                ('data_wyslania', models.DateTimeField(blank=True, null=True)),
                ('zatwierdzony_przez_prezydium', models.BooleanField(default=False)),
                ('data_zatwierdzenia', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='komisja_wnioski', to=settings.AUTH_USER_MODEL)),
                ('komisja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='core.komisja')),
                ('punkt_obrad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.komisjapunktobrad')),
                ('sesja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.komisjasesja')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
