# Generated by Django 5.1 on 2026-02-10 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_komisja_komisjasesja_komisjapunktobrad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wniosek',
            options={'ordering': ['-data']},
        ),
        migrations.AddField(
            model_name='wniosek',
            name='sygnatura',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='punkt_obrad',
            field=models.ForeignKey(blank=True, help_text='Jeśli puste, wniosek jest złożony poza sesją.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='core.punktobrad'),
        ),
    ]
