# Generated by Django 5.1 on 2026-02-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_wniosek_options_wniosek_sygnatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wniosek',
            name='typ',
            field=models.CharField(choices=[('wniosek', 'Wniosek'), ('zwo_sesji', 'Zwołanie sesji'), ('proj_uchwaly', 'Projekt uchwały'), ('zapytanie', 'Zapytanie')], default='wniosek', max_length=20),
        ),
    ]
