# Generated by Django 5.1 on 2026-04-05 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sesja_opis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KomisjaGlosowanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('otwarte', models.BooleanField(default=False)),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('jawnosc', models.CharField(choices=[('jawne', 'Jawne'), ('tajne', 'Tajne')], default='jawne', max_length=10)),
                ('wiekszosc', models.CharField(choices=[('zwykla', 'Większość zwykła'), ('bezwzgledna', 'Większość bezwzględna')], default='zwykla', max_length=15)),
                ('liczba_uprawnionych', models.PositiveIntegerField(blank=True, help_text='Jeśli puste, system przyjmie liczbę oddanych głosów jako bazę dla większości bezwzględnej.', null=True)),
                ('punkt_obrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosowania', to='core.komisjapunktobrad')),
            ],
            options={
                'ordering': ['-utworzone'],
            },
        ),
        migrations.CreateModel(
            name='KomisjaGlos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glos', models.CharField(choices=[('za', 'Za'), ('przeciw', 'Przeciw'), ('wstrzymuje', 'Wstrzymuję się')], max_length=10)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisja_glosy', to=settings.AUTH_USER_MODEL)),
                ('glosowanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosy', to='core.komisjaglosowanie')),
            ],
            options={
                'ordering': ['uzytkownik'],
                'unique_together': {('glosowanie', 'uzytkownik')},
            },
        ),
    ]
