# Generated by Django 5.1 on 2026-04-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_komisjaglosowanie_komisjaglos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glos',
            options={'ordering': ['uzytkownik'], 'verbose_name': 'Głos', 'verbose_name_plural': 'Głosy'},
        ),
        migrations.AlterModelOptions(
            name='glosowanie',
            options={'verbose_name': 'Głosowanie', 'verbose_name_plural': 'Głosowania'},
        ),
        migrations.AlterModelOptions(
            name='kandydat',
            options={'verbose_name': 'Kandydat', 'verbose_name_plural': 'Kandydaci'},
        ),
        migrations.AlterModelOptions(
            name='komisja',
            options={'ordering': ['nazwa'], 'verbose_name': 'Komisja', 'verbose_name_plural': 'Komisje'},
        ),
        migrations.AlterModelOptions(
            name='komisjaglos',
            options={'ordering': ['uzytkownik'], 'verbose_name': 'Głos komisji', 'verbose_name_plural': 'Głosy komisji'},
        ),
        migrations.AlterModelOptions(
            name='komisjaglosowanie',
            options={'ordering': ['-utworzone'], 'verbose_name': 'Głosowanie komisji', 'verbose_name_plural': 'Głosowania komisji'},
        ),
        migrations.AlterModelOptions(
            name='komisjapunktobrad',
            options={'ordering': ['numer'], 'verbose_name': 'Punkt obrad komisji', 'verbose_name_plural': 'Punkty obrad komisji'},
        ),
        migrations.AlterModelOptions(
            name='komisjasesja',
            options={'ordering': ['-data'], 'verbose_name': 'Sesja komisji', 'verbose_name_plural': 'Sesje komisji'},
        ),
        migrations.AlterModelOptions(
            name='komisjawniosek',
            options={'ordering': ['-data'], 'verbose_name': 'Wniosek komisji', 'verbose_name_plural': 'Wnioski komisji'},
        ),
        migrations.AlterModelOptions(
            name='obecnosc',
            options={'ordering': ['radny__nazwisko', 'radny__imie'], 'verbose_name': 'Obecność', 'verbose_name_plural': 'Obecności'},
        ),
        migrations.AlterModelOptions(
            name='punktobrad',
            options={'ordering': ['numer'], 'verbose_name': 'Punkt obrad', 'verbose_name_plural': 'Punkty obrad'},
        ),
        migrations.AlterModelOptions(
            name='sesja',
            options={'ordering': ['data'], 'verbose_name': 'Sesja', 'verbose_name_plural': 'Sesje'},
        ),
        migrations.AlterModelOptions(
            name='wniosek',
            options={'ordering': ['-data'], 'verbose_name': 'Wniosek', 'verbose_name_plural': 'Wnioski'},
        ),
        migrations.AddField(
            model_name='sesja',
            name='jest_zamknieta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='glosowanie',
            name='liczba_uprawnionych',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='komisjaglosowanie',
            name='liczba_uprawnionych',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='punkt_obrad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wnioski', to='core.punktobrad'),
        ),
    ]
