# Generated by Django 5.1 on 2026-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_glos_options_alter_glosowanie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glosowanie',
            name='kandydaci',
            field=models.ManyToManyField(blank=True, related_name='glosowania', to='core.kandydat'),
        ),
    ]
