# Generated by Django 5.1 on 2026-04-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_glosowanie_kandydaci"),
    ]

    operations = [
        migrations.AddField(
            model_name="komisjasesja",
            name="aktywny_punkt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.komisjapunktobrad",
            ),
        ),
    ]
