# Generated by Django 5.1 on 2026-04-17 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_komisjasesja_aktywny_punkt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="komisja",
            name="czlonkowie",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(("rola__in", ["radny", "prezydium", "administrator"])),
                related_name="komisje",
                to="accounts.uzytkownik",
            ),
        ),
        migrations.AlterField(
            model_name="komisja",
            name="przewodniczacy",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("rola__in", ["radny", "prezydium", "administrator"])),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="komisje_przewodniczy",
                to="accounts.uzytkownik",
            ),
        ),
    ]
