# Generated by Django 5.1 on 2026-04-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_komisja_czlonkowie_alter_komisja_przewodniczacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomisjaPodpunktObrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('tytul', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
                ('aktywny', models.BooleanField(default=False)),
                ('punkt_nadrzedny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podpunkty', to='core.komisjapunktobrad')),
            ],
            options={
                'verbose_name': 'Podpunkt obrad komisji',
                'verbose_name_plural': 'Podpunkty obrad komisji',
                'ordering': ['punkt_nadrzedny__numer', 'numer'],
            },
        ),
        migrations.AddField(
            model_name='komisjaglosowanie',
            name='podpunkt_obrad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glosowania', to='core.komisjapodpunktobrad'),
        ),
        migrations.AddField(
            model_name='komisjasesja',
            name='aktywny_podpunkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.komisjapodpunktobrad'),
        ),
        migrations.CreateModel(
            name='PodpunktObrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('tytul', models.CharField(max_length=300)),
                ('opis', models.TextField(blank=True)),
                ('aktywny', models.BooleanField(default=False)),
                ('punkt_nadrzedny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podpunkty', to='core.punktobrad')),
            ],
            options={
                'verbose_name': 'Podpunkt obrad',
                'verbose_name_plural': 'Podpunkty obrad',
                'ordering': ['punkt_nadrzedny__numer', 'numer'],
            },
        ),
        migrations.AddField(
            model_name='glosowanie',
            name='podpunkt_obrad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glosowania', to='core.podpunktobrad'),
        ),
        migrations.AddField(
            model_name='sesja',
            name='aktywny_podpunkt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.podpunktobrad'),
        ),
        migrations.AddConstraint(
            model_name='komisjapodpunktobrad',
            constraint=models.UniqueConstraint(fields=('punkt_nadrzedny', 'numer'), name='uniq_komisjapodpunktobrad_punkt_numer'),
        ),
        migrations.AddConstraint(
            model_name='podpunktobrad',
            constraint=models.UniqueConstraint(fields=('punkt_nadrzedny', 'numer'), name='uniq_podpunktobrad_punkt_numer'),
        ),
    ]
