# Generated by Django 5.1 on 2025-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
