# Generated by Django 5.1 on 2026-02-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_uzytkownik_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzytkownik',
            name='rola',
            field=models.CharField(choices=[('radny', 'Radny'), ('prezydium', 'Prezydium'), ('administrator', 'Administrator')], default='radny', max_length=15),
        ),
    ]
